### ISSUE TITLE
So close, but not close enough

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/this-site-aint-no-sloth#1]
@charlie-quinn

Hey Charlie - Visually there are a couple things that look a little off, but I cant seem to fix them enough to push it through markbot

**Comment by charlie-quinn** [comment]
An email was sent to both you school and personal accounts regarding this assignment.

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️Reminder: please close this issue once it has been resolved.
